[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
payment = "5APtDhWVsehsQM4yoqPTzy36EJJLRBLVxXy9ApCK6BeH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"  # Localnet, devnet, testnet, mainnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[workspace]
types = "app/src/idl/"

[test]
startup_wait = 10000
# validator = { url = "localhost:8899" }
