[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
payment = "CVnY7DzpU5TcJa8DyW4Nsgv2DVGWKHxWca1grt3EqKWT"
ed25519_program = "Ed25519SigVerify111111111111111111111111111"

[programs.devnet]
payment = "CVnY7DzpU5TcJa8DyW4Nsgv2DVGWKHxWca1grt3EqKWT"
ed25519_program = "Ed25519SigVerify111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"  # Localnet, devnet, testnet, mainnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
deploy = "anchor migrate --provider.cluster devnet"

[workspace]
types = "app/src/idl/"

[test]
startup_wait = 10000
# validator = { url = "https://api.devnet.solana.com" }
# validator = { url = "localhost:8899" }
